"""inclusao de campo na tabela contato

Revision ID: 34116fb525e7
Revises: 1f80939d696b
Create Date: 2026-02-09 15:35:05.823462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34116fb525e7'
down_revision = '1f80939d696b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('respondi', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.drop_column('respondi')

    # ### end Alembic commands ###
